// Generated by gencpp from file message/CommandInformation.msg
// DO NOT EDIT!


#ifndef MESSAGE_MESSAGE_COMMANDINFORMATION_H
#define MESSAGE_MESSAGE_COMMANDINFORMATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message
{
template <class ContainerAllocator>
struct CommandInformation_
{
  typedef CommandInformation_<ContainerAllocator> Type;

  CommandInformation_()
    : commandId(0)
    , actionPoseX(0.0)
    , actionPoseY(0.0)  {
    }
  CommandInformation_(const ContainerAllocator& _alloc)
    : commandId(0)
    , actionPoseX(0.0)
    , actionPoseY(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _commandId_type;
  _commandId_type commandId;

   typedef double _actionPoseX_type;
  _actionPoseX_type actionPoseX;

   typedef double _actionPoseY_type;
  _actionPoseY_type actionPoseY;




  typedef boost::shared_ptr< ::message::CommandInformation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message::CommandInformation_<ContainerAllocator> const> ConstPtr;

}; // struct CommandInformation_

typedef ::message::CommandInformation_<std::allocator<void> > CommandInformation;

typedef boost::shared_ptr< ::message::CommandInformation > CommandInformationPtr;
typedef boost::shared_ptr< ::message::CommandInformation const> CommandInformationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message::CommandInformation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message::CommandInformation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'message': ['/home/maksim/test/workspace_lab2/src/message/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::message::CommandInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message::CommandInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message::CommandInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message::CommandInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::CommandInformation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::CommandInformation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message::CommandInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc58e2467e5237bf155570b7d7721c7f";
  }

  static const char* value(const ::message::CommandInformation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc58e2467e5237bfULL;
  static const uint64_t static_value2 = 0x155570b7d7721c7fULL;
};

template<class ContainerAllocator>
struct DataType< ::message::CommandInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message/CommandInformation";
  }

  static const char* value(const ::message::CommandInformation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message::CommandInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 commandId \n\
float64 actionPoseX\n\
float64 actionPoseY\n\
";
  }

  static const char* value(const ::message::CommandInformation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message::CommandInformation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.commandId);
      stream.next(m.actionPoseX);
      stream.next(m.actionPoseY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CommandInformation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message::CommandInformation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message::CommandInformation_<ContainerAllocator>& v)
  {
    s << indent << "commandId: ";
    Printer<int8_t>::stream(s, indent + "  ", v.commandId);
    s << indent << "actionPoseX: ";
    Printer<double>::stream(s, indent + "  ", v.actionPoseX);
    s << indent << "actionPoseY: ";
    Printer<double>::stream(s, indent + "  ", v.actionPoseY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_MESSAGE_COMMANDINFORMATION_H
